### PR TITLE
refactor(IbanInput): Make IbanInput onChange prop optional

### PR DESCRIPTION
**Pull request by ruheni**
### What this PR does

Make `onChange` prop for `IbanInput` component optional

### Why is this needed?

Please include relevant motivation and context of why this PR is necessary, sentry/linear/notion/...

Solves:
EMU-7135

### How to test?

_Please include additional context on how to test this PR._

### Checklist:

- [ ] I reviewed my own code
- [ ] The changes align with the designs I received  
  Or give a reason why this does not apply:
- [ ] I have attached screenshot(s), video(s) or gif(s) showing that the solution is working as expected  
  Or give a reason why this does not apply:
- [ ] I have updated the task(s) status on Linear
- [ ] All new media is optimized (images, gifs, videos)

### Browser support

My code works in the following browsers:

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by talo242** [comment]
@ruheni there were some open questions on the Linear issue. Did you validate those?
If so, can you provide more context/examples in this PR?

**Comment by talo242** [comment]
@ruheni any updates on this PR?

**Comment by ruheni** [comment]
I'll go ahead and answer the questions raised in the issue in this PR

> 1. How pre-fill values if using `IbanInput` as an uncontrolled component?
> 		a. Maybe exposing a `defaultValue` prop and using that instead of `value`

I've updated the `value` prop to `defaultValue`. I think that would make it work better as an uncontrolled component

> 2. Is there a chance that the internal state could go out of sync with any potential external state when using `IbanInput` as controlled component?

No. I don't think so at least. On testing out the `CurrencyInput` component in the `app` repo, the value on form submission is what the user inputs

**Comment by ruheni** [comment]
Closing this for now. Let's revisit this in future.

**Pull request closed without merging**
