### PR TITLE
refactor(cards): Remove legacy cards

### PR DESCRIPTION
**Pull request by diogomateus**
### What this PR does
This PR removes the legacy cards:
- CardWithLeftIcon
- CardWithTopLeftIcon
- CardWithTopIcon

### How to test?

_Please include additional context on how to test this PR._

### Checklist:

- [ ] I reviewed my own code
- [ ] The changes align with the designs I received  
  Or give a reason why this does not apply:
- [ ] I have attached screenshot(s), video(s) or gif(s) showing that the solution is working as expected  
  Or give a reason why this does not apply:
- [ ] I have updated the task(s) status on Linear
- [ ] All new media is optimized (images, gifs, videos)

### Browser support

My code works in the following browsers:

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by a-maffei — COMMENTED** [review]
The cards are still in use on the website and app - would you replace them with the more recent ones once you update the package?

Update: I've just seen the other PRs 😃

**Comment by diogomateus** [comment]
> The cards are still in use on the website and app - would you replace them with the more recent ones once you update the package?

Yeah, just created a few PRs with it. Won't merge this and release until they're ready and stable

**Review by a-maffei — APPROVED** [review]

**Review by talo242 — APPROVED** [review]

**Comment by talo242** [comment]
@diogomateus don't forget to mark the release that includes this PR as a breaking change.

**Comment by diogomateus** [comment]
> @diogomateus don't forget to mark the release that includes this PR as a breaking change.

Will do! Still need a tiny update on `app` before merging this but I'll try to merge this next week and not get it holding for too much long

**Review by kimkwanka — APPROVED** [review]

**Pull request merged**
